apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcr-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: gcr.io/es-devops-sb/gcr:1.0
        ports:
        - containerPort: 80
